# Generated by Django 3.0.6 on 2020-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_color', models.CharField(max_length=100)),
                ('fav_hero', models.CharField(max_length=100)),
                ('fav_movie', models.CharField(max_length=100)),
                ('fav_song', models.CharField(max_length=100)),
                ('fav_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
