# Generated by Django 3.0.6 on 2020-06-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='user_type_name',
            field=models.CharField(blank=True, choices=[('employer', 'employer'), ('jobseeker', 'jobseeker')], default='jobseeker', max_length=10),
        ),
    ]
