# Generated by Django 3.0.6 on 2020-06-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
