# Generated by Django 3.0.6 on 2020-06-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200622_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='user_type_name',
            field=models.CharField(choices=[('employer', 'employer'), ('jobseeker', 'jobseeker')], default='jobseeker', max_length=10),
        ),
    ]
