# Generated by Django 3.0.6 on 2020-06-03 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Accounts', '0002_delete_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type_name', models.CharField(choices=[('employer', 'employer'), ('jobseeker', 'jobseeker')], default='jobseeker', max_length=10)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('current_city', models.CharField(max_length=30)),
            ],
        ),
    ]
