# Generated by Django 3.0.6 on 2020-06-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
