# Generated by Django 3.0.6 on 2020-06-04 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20200603_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
