# Generated by Django 3.0.6 on 2020-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20200604_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
