# Generated by Django 3.0.6 on 2020-06-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker_basic',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.User_type')),
                ('profile_picture', models.ImageField(default='../static/images/default_profile_picture.png', upload_to='pictures/')),
                ('salary_expectation', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('highest_education', models.CharField(default='none', max_length=50)),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('job_type_name', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker_skill_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField()),
                ('skill_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobseeker.Skill_set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobseeker.Jobseeker_basic')),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(default='Full Time', max_length=20)),
                ('job_title', models.CharField(max_length=60)),
                ('company_name', models.CharField(max_length=60)),
                ('job_location_city', models.CharField(max_length=30)),
                ('job_description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobseeker.Jobseeker_basic')),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(default='', max_length=40)),
                ('degree_name', models.CharField(default='', max_length=70)),
                ('institute', models.CharField(max_length=70)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cgpa', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobseeker.Jobseeker_basic')),
            ],
        ),
    ]
