# Generated by Django 3.0.6 on 2020-06-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_basic',
            name='job_type_name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
