# Generated by Django 3.0.6 on 2020-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobseeker', '0002_auto_20200616_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_basic',
            name='highest_education',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
