# Generated by Django 3.0.6 on 2020-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobseeker', '0004_auto_20200618_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_experience',
            name='job_type',
            field=models.CharField(default='Full Time', max_length=20),
        ),
    ]
