# Generated by Django 3.0.6 on 2020-06-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobseeker', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(default='../static/images/default_company_logo.png', upload_to='company_logos')),
                ('company_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employer_basic',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.User_type')),
                ('profile_picture', models.ImageField(default='../static/images/default_profile_picture.png', upload_to='pictures/')),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Employer.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company_name_hidden', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('job_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('job_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Job_location')),
            ],
        ),
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job_post_skill_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Job_post')),
                ('skill_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobseeker.Skill_set')),
            ],
        ),
        migrations.CreateModel(
            name='Job_post_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('applied_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobseeker.Jobseeker_basic')),
                ('job_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Job_post')),
            ],
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Job_type'),
        ),
        migrations.AddField(
            model_name='job_post',
            name='posted_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Employer_basic'),
        ),
    ]
