# Generated by Django 3.0.6 on 2020-06-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.TextField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Company')),
                ('posted_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Employer_basic')),
            ],
        ),
    ]
