# Generated by Django 3.0.6 on 2020-06-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='is_fresher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job_post',
            name='is_work_from_home',
            field=models.BooleanField(default=False),
        ),
    ]
