# Generated by Django 3.0.6 on 2020-06-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_auto_20200629_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='is_fresher',
        ),
        migrations.AddField(
            model_name='job_post',
            name='min_experience',
            field=models.IntegerField(default=0),
        ),
    ]
