# Generated by Django 3.0.6 on 2020-06-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_auto_20200616_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='max_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_post',
            name='min_salary',
            field=models.IntegerField(default=0),
        ),
    ]
