# Generated by Django 3.0.6 on 2020-06-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0004_auto_20200616_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='job_type_id',
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_type_name',
            field=models.CharField(default='Not Selected', max_length=50),
        ),
    ]
