# Generated by Django 3.0.6 on 2020-06-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_auto_20200620_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='job_title',
            field=models.CharField(default='Job Post', max_length=200),
        ),
    ]
