# Generated by Django 3.0.6 on 2020-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_auto_20200629_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_location',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
