# Generated by Django 3.0.6 on 2020-07-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0011_auto_20200701_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job_post_activity',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
